version: "3.8"
services:
  postgre_1:
    build: ./database
    restart: always
    env_file:
      - ./env/postgre.env
    volumes:
      - data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - logs:/app/Logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - postgre_1

volumes:
  data:
  logs:
